### ISSUE TITLE
Serialization of 'SimpleXMLElement' is not allowed

### ISSUE THREAD

**Issue by todordev** [YJSGframework/yjsg#9]
It is an error that blocks the whole system ( Joomla! v3.3.6 ).

I have installed the plugin **System - Yjsg Framework** and the template [YouMagazine](http://www.youjoomla.com/joomla-templates/youmagazine-news-joomla-template.html).

The template has to be selected to be used on front-end.

When I enable Joomla! debug from Global Configuration, the system stops and display that message.
**_Serialization of 'SimpleXMLElement' is not allowed_**

**Comment by fruiz500** [comment]
Not working!

I just installed the new framework from the website (2.1.3), and my Joomla 3.0 site locked up with this error. I can't do anything. Please help.

**Comment by danyj** [comment]
@fruiz500 you need to install git plugin version. The fix is to be released for next plugin version but master already has it in 
https://github.com/YJSGframework/yjsg/archive/master.zip

**Comment by oliversaguibo** [comment]
I tried the master but not working, i have dailynews templates installed on my joomla, When in debug mode i still got this error: 0 Serialization of 'SimpleXMLElement' is not allowed

Another weird thing is, i have jomsocial social installed and everytime i go to jomsocial all events i also got this error: 0 Serialization of 'SimpleXMLElement' is not allowed

**Comment by danyj** [comment]
@oliversaguibo   what joomla version are you on?  this bug was fixed 6 months ago and has not been reported since. please check and make sure you have all latest versions plugin and joomla

**Comment by oliversaguibo** [comment]
@danyj im using joomla version 3.4.1, Jomsocial is 4.0.5 and i got the later version of k2.

**Comment by danyj** [comment]
what version of YJSG do you have?

**Comment by oliversaguibo** [comment]
Version 2.2.2, i also tried the latest git version but still having the error.

**Comment by danyj** [comment]
@oliversaguibo  open a ticket at youjoomla and post your login info
